### ISSUE TITLE
Add more icons

### ISSUE THREAD

**Issue by wyze** [wyze/atom-flexicons#1]
Pull current open requests from the following repos:
- [wyze/seti-icons](https://github.com/wyze/seti-icons)
- [jesseweed/seti-ui](https://github.com/jesseweed/seti-ui)

**Comment by aethant** [comment]
Go/golang, please

**Comment by aethant** [comment]
Handlebars &/ Mustache, please.
 (.hbs/.handlebars extensions)

**Comment by wyze** [comment]
[v1.0.0](https://github.com/wyze/atom-flexicons/releases/tag/v1.0.0) shipped! :tada:
