### ISSUE TITLE
Theme compatibility

### ISSUE THREAD

**Issue by wyze** [wyze/atom-flexicons#7]
Need to check compatibility with a few more themes. Currently only test with One Dark.

**Comment by aethant** [comment]
> One Light - works
> Seti - Seti icons only appear when there isn't a flexicon icon
> Run Time - icons have a weird tint over them (seems brownish?)
> Nucleus Dark - works
> Direct Flat - works
> Codeacademy Atom - works
> Atom Material - works, but icons seem small given spacing/padding of theme and Material Design overall
> Atom Light - works
> Atom Dark - works

**Comment by wyze** [comment]
Awesome work here @aethant! :+1: 

I will check out the ones that just didn't "work" and make any necessary adjustments.

**Comment by wyze** [comment]
[v1.0.0](https://github.com/wyze/atom-flexicons/releases/tag/v1.0.0) shipped! :tada:
